### ISSUE TITLE
Write feeds spreadsheet

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/cold#36]
Make sure that the exported spreadsheet is the exact same as was imported

**Comment by rsdoiel** [comment]
I think this works. Want to watch things a bit longer to be sure.  I decided to wait to turn on the cronjobs until next week (Nov.  4).

**Comment by rsdoiel** [comment]
This is working in production and being used to generate CaltechPEOPLE and CaltechGROUPS for feeds now.
