### ISSUE TITLE
Links in landing page

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/cold#41]
On https://apps.library.caltech.edu/cold/admin/people/Wennberg-P-O, for example link 

CaltechAUTHORS ID to https://authors.library.caltech.edu/search?q=metadata.creators.person_or_org.identifiers.identifier%3A%22Wennberg-P-O%22&l=list&p=1&s=10&sort=bestmatch
archivespace https://collections.archives.caltech.edu/agents/people/2813
ORCID https://orcid.org/0000-0002-6126-3854
IMSS user id https://directory.caltech.edu/personnel/wennberg
CaltechTHESIS ID https://thesis.library.caltech.edu/view/author/Dabiri-John-Oluseun.html
CaltechTHESIS Advisor ID https://thesis.library.caltech.edu/view/advisor/Dabiri-J-O.html

**Comment by rsdoiel** [comment]
The views/people.hbs template has been updated.
